export const glossary = [
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: 'Set Bits',
    definition: 'The number of bits that are set to 1 in the binary representation of a number.',
    tags: ['bit manipulation'],
  },
  {
    id: 0,
    term: 'Palindrome',
    definition: 'A palindrome is a string that reads the same forward and backward.',
    tags: ['string'],
  },
  {
    id: 0,
    term: 'Subsequence',
    definition:
      'A subsequence is a sequence that can be derived from another sequence by deleting some or no elements without changing the order of the remaining elements.',
    tags: [],
  },
  {
    id: 0,
    term: 'Substring',
    definition: 'A substring is a contiguous sequence of characters within a string.',
    tags: [],
  },
  {
    id: 0,
    term: 'Subset',
    definition: 'A subset is a collection of elements that are all members of another set.',
    tags: [],
  },
  {
    id: 0,
    term: 'Power Set',
    definition: 'The power set of a set is the set of all possible subsets of that set.',
    tags: [],
  },
  {
    id: 0,
    term: 'Factorial',
    definition:
      'The factorial of a number n is the product of all positive integers less than or equal to n. It is denoted by n!.',
    tags: [],
  },
  {
    id: 0,
    term: 'Subarray',
    definition: 'A subarray is a contiguous sequence of elements within an array.',
    tags: [],
  },
  {
    id: 0,
    term: 'Amortized analysis',
    definition:
      'Amortized analysis is a method for analyzing a collection of operations, where the cost of expensive operations is spread out over the entire sequence.',
    tags: [],
  },
  {
    id: 0,
    term: 'Lexicographically',
    definition: 'Lexicographically means in dictionary order.',
    tags: [],
  },
  {
    id: 0,
    term: 'Hamming Weight',
    definition: 'The number of bits set to 1 in the binary representation of a number.',
    tags: ['bit manipulation'],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
  {
    id: 0,
    term: '',
    definition: '',
    tags: [],
  },
]
